// See https://aka.ms/new-console-template for more information
bool fartStatus = true;
fartStatus = false;
Console.WriteLine(fartStatus);
double numberOfFarts = 3.5e20;
numberOfFarts = -2e20;
Console.WriteLine(numberOfFarts);
float numberOfFartsBigger = 1.5e20F;
numberOfFartsBigger = 2e20F;
Console.WriteLine(numberOfFartsBigger);
decimal numberOfJewishFarts = 1e-20M;
numberOfJewishFarts = 1e-21M;
Console.WriteLine(numberOfJewishFarts);
int faaaart = 1000000;
faaaart = 123456;
Console.WriteLine(faaaart);
short smallFart = 50;
smallFart = 3;
Console.WriteLine(smallFart);
byte reallySmallFart = 10;
reallySmallFart = 15;
long prettyBigFart = 9200000000L;
prettyBigFart = 9500000000;
Console.WriteLine(prettyBigFart);
sbyte negFart = -10;
negFart = -2;
Console.WriteLine(negFart);
ushort mediumFawrts = 50000;
mediumFawrts = 6000;
Console.WriteLine(mediumFawrts);
uint sniff = 3000000;
sniff = 3000;
Console.WriteLine(sniff);
ulong lotsOfFarts = 1000000000000UL;
lotsOfFarts = 200000000000000;
Console.WriteLine(lotsOfFarts);
char aLetter = 'b';
aLetter = 'c';
Console.WriteLine(aLetter);
string aSmellyString = "I have lots of farts in my poop chute";
aSmellyString = "I can't stop farting";
Console.WriteLine(aSmellyString);
